# Make sure to update it as per your region and identities before using it
# https://docs.databricks.com/gcp/en/resources/ip-domain-region#private-service-connect-psc-attachment-uris-and-project-numbers
# Find your regional control plane VPC host project
# If your workspace url is 31171674993667.7.gcp.databricks.com
# WORKSPACEID = 311716749948597
- ingressFrom:
    identities:
    #   - group:group@corp.com
    #   - user:user@corp.com
      - serviceAccount:db-[WORKSPACEID]@prod-gcp-[GEO]-[REGION].iam.gserviceaccount.com
    sources:
    # https://docs.databricks.com/gcp/en/resources/ip-domain-region#private-service-connect-psc-attachment-uris-and-project-numbers
    # Find your regional control plane VPC host project #
    # Databricks regional control plane project (us-east1)
      - resource: projects/51066298900
  ingressTo:
    operations:
      # Compute Engine operations
      - methodSelectors:
          - methodSelectors:
          - method: 'NetworksService.Get'
          - method: 'ProjectsService.Get'
          - method: 'FirewallsService.Get'
          - method: 'SubnetworksService.Get'
          - method: 'SubnetworksService.SetPolicy'
          - method: 'SubnetworksService.GetPolicy'
          - method: 'InstancesService.List'
          - method: 'InstancesService.Get'
          - method: 'InstancesService.BulkInsert'
          - method: 'InstancesService.Delete'
          - method: 'InstancesService.SetLabels'
          - method: 'DisksService.List'
          - method: 'DisksService.Get'
          - method: 'DisksService.SetLabels'
          - method: 'ZonesService.List'
          - method: 'RegionsService.List'
          - method: 'RegionsService.Get'
          - method: 'GlobalOperationsService.Get'
          - method: 'RegionOperationsService.List'
          - method: 'ZoneOperationsService.List'
          - method: 'ZoneOperationsService.Get'
        serviceName: compute.googleapis.com
      # At the time of writing this, vpc sc didnt allow to filter calls by method
      # This is the only call we need google.api.serviceusage.v1.ServiceUsage.ListServices
      - methodSelectors:
          - method: '*'
        serviceName: serviceusage.googleapis.com
      # This is required to attach databricks-compute GSA to the databricks clusters
      # This is also required if you are using workload identity feature as explained here:
      # https://docs.databricks.com/gcp/en/compute/configure#google-service-account
      - methodSelectors:
          - method: 'Projects.SetIamPolicy' 
        serviceName: cloudresourcemanager.googleapis.com
      # IAM operations
      - methodSelectors:
          - method: 'IAM.GetIamPolicy'
          - method: 'IAM.GetServiceAccount'
        serviceName: iam.googleapis.com
    resources:
      - projects/1039757121236 # customer vpc project
      - projects/488622148875  # customer workspace project

# Calls could originate from several databricks regional projects:
# control plane (prod-* projects) - identity: db-workspaceId*
# unity catalog (uc-* projects) - identity: uc-*
# serverless compute plane (nw-* projects) - identity: db-workspaceId* or uc-*
# Find project numbers here:https://docs.databricks.com/gcp/en/resources/ip-domain-region#private-service-connect-psc-attachment-uris-and-project-numbers
# UC identities here: https://docs.databricks.com/gcp/en/sql/language-manual/sql-ref-syntax-aux-describe-credential
# Its a GCP Service Account
- ingressFrom:
    identities:
    - serviceAccount:db-[WORKSPACEID]@prod-gcp-[GEO]-[REGION].iam.gserviceaccount.com
    # Based on your setup you may have multiple uc credentials GSA 
    - serviceAccount:db-uc-credential-06akrlmcak-xn@uc-useast1.iam.gserviceaccount.com
    sources:
      # Databricks regional control plane project
      - resource: projects/51066298900 #prod-gcp-us-east1
      # Databricks regional unity-catalog project
      - resource: projects/234110679923 #uc-useast1
      # Databricks regional serverless compute plane project
      - resource: projects/126714886954 #nw-prod-useast1-01
  ingressTo:
    operations:
# Google Cloud Storage operations
      - methodSelectors:
          - method: 'google.storage.objects.get'
          - method: 'google.storage.objects.list'
          - method: 'google.storage.objects.create'
          - method: 'google.storage.objects.delete'
          - method: 'google.storage.buckets.get'
          - method: 'google.storage.buckets.testIamPermissions'
        serviceName: storage.googleapis.com
    resources:
      - projects/488622148875 # customer workspace project
# Lakehouse Federation to BigQuery
- ingressFrom:
    identities:
    - serviceAccount:[YOUR-GSA-HAVING-BQ-ACCESS]@[PROJECT].iam.gserviceaccount.com
    sources:
      # Databricks regional serverless sql compute plane project
      - resource: projects/126714886954 #example: shown here nw-prod-useast1-01
  ingressTo:
    operations:
# Google Cloud Bigquery operations
      - methodSelectors:
          - method: 'BigQueryRead.CreateReadSession'
          - method: 'bigquery.tables.get'
          - method: 'bigquery.tables.getData'
          - method: 'bigquery.tables.list'
          - method: 'bigquery.tables.create'
          - method: 'bigquery.tables.update'
          - method: 'bigquery.tables.delete'
          - method: 'bigquery.tables.updateData'
          - method: 'bigquery.datasets.get'
          - method: 'bigquery.datasets.create'
          - method: 'bigquery.jobs.create'    
        serviceName: bigquery.googleapis.com
    resources:
      - projects/488622148875 # customer project where BQ dataset exists
  ## Databricks regional control plane project
  ## Only required if you are using CMK
  ## https://docs.databricks.com/gcp/en/security/keys/customer-managed-keys
- ingressFrom:
    sources:
    - project: projects/68422481410 # example: shown here prod-gcp-us-central1
    identities:
    - serviceAccount:db-[WORKSPACEID]@prod-gcp-[GEO]-[REGION].iam.gserviceaccount.com
  ingressTo:
    resources:
    - projects/488622148875 # customer project where workspace is deployed
    operations:
    - serviceName: cloudkms.googleapis.com
      methodSelectors:
      - method: google.cloud.kms.v1.KeyManagementService.Decrypt
      - method: google.cloud.kms.v1.KeyManagementService.Encrypt