# This block defines ingress rules for Databricks services running in us-east4 region (example)
- ingressFrom:
    # Identity type is specified using group email
    identities:
      - group:databricks-vpc-sc-ingress-group@databricks.com
    sources:
      # Databricks central project - only required at workspace creation (us-central1)
      - resource: projects/68422481410
      # Databricks regional control plane project (us-east4)
      - resource: projects/121886670913  
      # Databricks regional control plane project where serverless SQL (us-east4) compute runs.
      - resource: projects/16098739049
  ingressTo:
    operations:
      # Allows specific Google Cloud Storage operations
      - methodSelectors:
          - method: google.storage.objects.create
          - method: google.storage.objects.get
          - method: google.storage.objects.list
          - method: google.storage.objects.delete
          - method: google.storage.buckets.testIamPermissions
        serviceName: storage.googleapis.com
      # Allows specific Compute Engine operation
      - methodSelectors:
          - method: RegionsService.Get
        serviceName: compute.googleapis.com
      # Allows all Google Kubernetes Engine operations
      - methodSelectors:
          - method: '*'
        serviceName: container.googleapis.com
      # Required if you use workload identity
      # https://docs.gcp.databricks.com/en/archive/compute/configure.html#google-service-account
      - methodSelectors:
          - method: IAM.GetIamPolicy
          - method: IAM.SetIamPolicy
        serviceName: iam.googleapis.com
    resources:
      - projects/488622148875

# This block defines ingress rules for a specific user
- ingressFrom:
    identities:
      # To allow a user to access services
      # Not doing this would lock user from accessing any of the services under VPC
      # Helps with debugging or using GCP console or CLI
      - user:user@example.com
    sources:
      - accessLevel: '*'
  ingressTo:
    operations:
      # Allows all operations on all services
      - serviceName: '*'
    resources:
      - projects/546577047680
      - projects/488622148875
# Optional: Only required if you use audit logging delivery
# https://docs.gcp.databricks.com/en/admin/account-settings/audit-log-delivery.html
- ingressFrom:
    identities:
      - group:databricks-vpc-sc-ingress-group@databricks.com
    sources:
      - resource: projects/85638097580
  ingressTo:
    operations:
      # Allows specific Google Cloud Storage operations for audit log delivery
      - methodSelectors:
          - method: google.storage.objects.create
          - method: google.storage.objects.delete
          - method: google.storage.objects.get
          - method: google.storage.objects.list
          - method: google.storage.buckets.testIamPermissions
        serviceName: storage.googleapis.com
    resources:
      - projects/546577047680
      - projects/488622148875