"""New workspace: turn a baseline into a ready-to-run deployment folder.

The output is a new directory holding:

- the tested Terraform, copied from this repo (`terraform/`), or for an
  external source (the official Databricks SRA) clone instructions pinned to a
  reviewed commit;
- `inputs.tfvars`: the deployment's required variables, filled from
  `--set name=value` answers (unanswered ones are `REPLACE_ME_*`);
- one tfvars file per stage, layered on top of `inputs.tfvars`;
- a README with every command (plan -> assess -> apply -> verify).

Nothing existing is modified. The Terraform is used as-is; the user runs it
and `verify` checks the resulting state. Baselines without tested Terraform
have no `build` block, and `new` refuses rather than improvise.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
from pathlib import Path, PurePosixPath

from .catalog import CATALOG_ROOT

REPO_ROOT = CATALOG_ROOT.parent.parent
REPO_URL = "https://github.com/bhavink/databricks"
PLACEHOLDER = "REPLACE_ME"
# Set from the environment, never written to files.
DEFAULT_ENV = ("databricks_account_id",)
# Copied into bundles. Anything else (tfvars, state, .terraform, lock files) never is.
BUNDLE_SUFFIXES = (".tf", ".tftest.hcl")
BUNDLE_NAMES = ("terraform.tfvars.example", "README.md")
_LOCAL_SOURCE = re.compile(r'^\s*source\s*=\s*"(\.{1,2}/[^"]+)"', re.M)


# ---------------------------------------------------------------- variables

def _variable_blocks(text: str):
    for m in re.finditer(r'^variable\s+"([A-Za-z0-9_]+)"\s*\{', text, re.M):
        i, depth = m.end(), 1
        while depth and i < len(text):
            depth += {"{": 1, "}": -1}.get(text[i], 0)
            i += 1
        yield m.group(1), text[m.end():i - 1]


def deployment_variables(directory: Path) -> dict[str, dict]:
    """name -> {"required": bool, "description": str} from every *.tf in a root."""
    out = {}
    for tf in sorted(directory.glob("*.tf")):
        for name, body in _variable_blocks(tf.read_text(encoding="utf-8")):
            desc = re.search(r'^\s*description\s*=\s*"((?:[^"\\]|\\.)*)"', body, re.M)
            out[name] = {
                "required": not re.search(r"^\s*default\s*=", body, re.M),
                "description": desc.group(1) if desc else "",
            }
    return out


def declared_variables(deployment: str, repo_root: Path = REPO_ROOT) -> set[str]:
    return set(deployment_variables(repo_root / deployment))


def build_variables(build: dict, repo_root: Path = REPO_ROOT) -> dict[str, dict]:
    """Variables of the build's Terraform root: parsed from the repo, or the
    catalog's CI-verified copy for an external source."""
    if "deployment" in build:
        return deployment_variables(repo_root / build["deployment"])
    src = build["source"]
    return {name: {"required": name in src["required"], "description": ""} for name in src["variables"]}


# ---------------------------------------------------------------- rendering

def _hcl(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list):
        return "[" + ", ".join(_hcl(v) for v in value) + "]"
    if isinstance(value, dict):
        return "{ " + ", ".join(f"{k} = {_hcl(v)}" for k, v in sorted(value.items())) + " }"
    raise ValueError(f"unsupported tfvars value: {value!r}")


def _tfvars(header: list[str], values: dict) -> str:
    lines = header + [""]
    if values:
        width = max(len(k) for k in values)
        lines += [f"{k:<{width}} = {_hcl(v)}" for k, v in sorted(values.items())]
    return "\n".join(lines) + "\n"


def render_tfvars(baseline: dict, stage: dict, index: int) -> str:
    return _tfvars([
        f"# Stage {index}: {stage['name']} — baseline {baseline['id']}",
        "# Generated by wa-agent new. Layered after inputs.tfvars; later -var-file arguments win.",
    ], stage["tfvars"])


def parse_answer(raw: str):
    """`--set` value: JSON when it parses (lists, booleans, numbers, objects), else a string."""
    try:
        return json.loads(raw)
    except ValueError:
        return raw


def resolve_inputs(baseline: dict, answers: dict | None, repo_root: Path = REPO_ROOT) -> dict:
    """Values for inputs.tfvars: required variables (except env-provided ones) plus any answered ones."""
    build = baseline["build"]
    variables = build_variables(build, repo_root)
    env = set(build.get("env", DEFAULT_ENV))
    answers = dict(answers or {})
    for name in sorted(answers):
        if name not in variables:
            raise ValueError(f"--set {name}: not a variable of {_where(build)}")
        if name in env:
            raise ValueError(f"--set {name}: set it with TF_VAR_{name} instead; it is never written to files")
    values = {name: f"{PLACEHOLDER}_{name}" for name, v in variables.items() if v["required"] and name not in env}
    values.update(answers)
    return values


def placeholders(build: dict, inputs: dict | None = None) -> list[str]:
    found = set()
    sources = [stage["tfvars"] for stage in build["stages"]] + [inputs or {}]
    for tfvars in sources:
        for key, value in tfvars.items():
            values = value if isinstance(value, list) else [value]
            if any(isinstance(v, str) and v.startswith(PLACEHOLDER) for v in values):
                found.add(key)
    return sorted(found)


def _where(build: dict) -> str:
    if "deployment" in build:
        return build["deployment"]
    src = build["source"]
    return f"{src['repo']}/tree/{src['ref']}/{src['path']}"


def check_build(baseline: dict, repo_root: Path = REPO_ROOT) -> None:
    build = baseline.get("build")
    if not build:
        raise ValueError(
            f"baseline {baseline['id']!r} has no tested deployment yet; see {baseline['deployment']} "
            f"and the official docs. The agent does not improvise Terraform."
        )
    declared = set(build_variables(build, repo_root))
    for stage in build["stages"]:
        unknown = sorted(set(stage["tfvars"]) - declared)
        if unknown:
            raise ValueError(f"baseline {baseline['id']} stage {stage['name']}: not variables of "
                             f"{_where(build)}: {unknown}")


# ---------------------------------------------------------------- bundling

def bundle_files(deployment: str, repo_root: Path = REPO_ROOT) -> list[str]:
    """Repo-relative paths of the deployment and every local module it uses, transitively."""
    seen, queue, files = set(), [PurePosixPath(deployment)], []
    while queue:
        rel = queue.pop()
        if rel in seen:
            continue
        seen.add(rel)
        directory = repo_root / rel
        for path in sorted(directory.rglob("*")):
            if not path.is_file() or ".terraform" in path.relative_to(directory).parts:
                continue
            if path.name.endswith(BUNDLE_SUFFIXES) or path.name in BUNDLE_NAMES:
                files.append(path.relative_to(repo_root).as_posix())
            if path.suffix == ".tf" and path.parent == directory:
                for src in _LOCAL_SOURCE.findall(path.read_text(encoding="utf-8")):
                    queue.append(PurePosixPath(_normalize(rel / src)))
    return sorted(set(files))


def _normalize(path: PurePosixPath) -> str:
    parts: list[str] = []
    for part in path.parts:
        if part == "..":
            if not parts:
                raise ValueError(f"module source escapes the repo: {path}")
            parts.pop()
        elif part != ".":
            parts.append(part)
    return "/".join(parts)


def source_commit(repo_root: Path = REPO_ROOT) -> str:
    try:
        out = subprocess.run(["git", "-C", str(repo_root), "rev-parse", "HEAD"],
                             capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return "unknown"
    return out.stdout.strip() if out.returncode == 0 else "unknown"


def matches_commit(paths: list[str], repo_root: Path = REPO_ROOT) -> bool | None:
    """True when the bundled files are exactly the committed ones; None without git."""
    try:
        out = subprocess.run(["git", "-C", str(repo_root), "status", "--porcelain", "--", *paths],
                             capture_output=True, text=True, timeout=10)
    except (OSError, subprocess.SubprocessError):
        return None
    return None if out.returncode != 0 else out.stdout.strip() == ""


# ---------------------------------------------------------------- run book

def render_readme(baseline: dict, inputs: dict, commit: str, book_dir: str = "<run-book-dir>") -> str:
    build = baseline["build"]
    stages = build["stages"]
    env = list(build.get("env", DEFAULT_ENV))
    bundled = "deployment" in build
    if bundled:
        dep = build["deployment"]
        workdir = f"terraform/{dep}"
        up = "/".join([".."] * (len(PurePosixPath(dep).parts) + 1))
        book = up  # relative, so the folder can be moved
        origin = f"[`{dep}`]({REPO_URL}/tree/{commit}/{dep}) at `{commit}`, copied into `terraform/`"
    else:
        src = build["source"]
        workdir = None
        book = book_dir
        origin = f"[`{src['path']}`]({src['repo']}/tree/{src['ref']}/{src['path']}) (official) at `{src['ref']}`"
    workspace = f" --workspace {build['workspace']}" if build.get("workspace") else ""

    lines = [
        f"# New workspace — {baseline['name']}",
        "",
        f"Baseline `{baseline['id']}`: {baseline['use_case'].strip()}",
        "",
        f"Tested Terraform: {origin}.",
        "",
        "> The agent changed nothing. You run every command below; verify afterwards.",
        "",
        "## 0. Prepare",
        "",
        "```bash",
    ]
    if bundled:
        lines += [f"cd {workdir}"]
    else:
        src = build["source"]
        lines += [
            f"git clone {src['repo']}.git sra && cd sra && git checkout {src['ref']}",
            f"cd {src['path']}",
        ]
    lines += [f"export TF_VAR_{name}=<{name}>   # bash/zsh; never commit it" for name in env]
    lines += [f"# PowerShell: $env:TF_VAR_{name} = \"<{name}>\"" for name in env]
    lines += ["terraform init", "```", ""]

    todo = placeholders(build, inputs)
    if todo:
        lines += ["Replace every `REPLACE_ME_*` value in `inputs.tfvars` and the stage files: "
                  + ", ".join(f"`{k}`" for k in todo) + ".", ""]
    lines += ["Optional settings (CIDRs, tags, CMK, …): add them to `inputs.tfvars`; see the deployment's",
              "`variables.tf`" + (" and `terraform.tfvars.example`." if bundled else "."), ""]

    var_files = [f"-var-file={book}/inputs.tfvars"]
    for i, stage in enumerate(stages, 1):
        var_files.append(f"-var-file={book}/stage-{i}-{stage['name']}.tfvars")
        lines += [f"## {i}. Stage: {stage['name']}", ""]
        if stage.get("note"):
            lines += [f"> {stage['note'].strip()}", ""]
        lines += [
            "```bash",
            f"terraform plan {' '.join(var_files)} -out stage{i}.plan",
            f"terraform show -json stage{i}.plan > stage{i}.plan.json",
            f"wa-agent collect tfplan --cloud azure --plan stage{i}.plan.json{workspace} -o stage{i}.facts.json",
            f"wa-agent assess --facts stage{i}.facts.json --baseline {baseline['id']} -o stage{i}.report.md",
            f"wa-agent diagram --tf-json stage{i}.plan.json{workspace} -o stage{i}.architecture.md   # what this stage deploys",
            f"terraform apply stage{i}.plan",
            "```",
            "",
        ]
    n = len(stages)
    lines += [
        f"## {n + 1}. Verify",
        "",
        "Check the deployed state against the baseline. Add live facts for controls that",
        "live outside Terraform state (e.g. manually approved NCC private endpoint rules).",
        "",
        "```bash",
        "terraform show -json > state.json",
        f"wa-agent verify --tf-json state.json{workspace} --baseline {baseline['id']} -o verify.md",
        f"wa-agent diagram --tf-json state.json{workspace} -o architecture.md   # as deployed",
        "# optional, from a network the workspace allows:",
        "wa-agent collect live --cloud azure --workspace <arm-id> --profile <ws> --account-profile <acct> -o live.facts.json",
        f"wa-agent verify --tf-json state.json{workspace} --facts live.facts.json --baseline {baseline['id']} -o verify-live.md",
        "```",
        "",
        "Intermediate stages are expected to show gaps (for example public access still on).",
    ]
    gaps = build.get("known_gaps") or []
    if gaps:
        lines += ["After the final stage, these gaps remain by design of the Terraform used; close them yourself:", ""]
        lines += [f"- `{g['check']}`: {g['reason'].strip()}" for g in gaps]
    else:
        lines += ["The final stage is the one that must verify as PASS."]
    lines += [
        "",
        "---",
        "",
        "_Provided as is, without warranty. Review and test before applying; you are responsible for what you deploy._",
        "",
    ]
    return "\n".join(lines)


def render(catalog: dict, baseline_id: str, answers: dict | None = None, repo_root: Path = REPO_ROOT,
           book_dir: str = "<run-book-dir>", commit: str | None = None) -> dict[str, str]:
    """File name -> content for a baseline's run book (Terraform bundle excluded). Writes nothing."""
    baselines = {b["id"]: b for b in catalog["baselines"]}
    if baseline_id not in baselines:
        raise ValueError(f"unknown baseline {baseline_id!r}; choose from {sorted(baselines)}")
    baseline = baselines[baseline_id]
    check_build(baseline, repo_root)
    build = baseline["build"]
    commit = commit or source_commit(repo_root)
    inputs = resolve_inputs(baseline, answers, repo_root)

    files = {"inputs.tfvars": _tfvars([
        f"# Inputs — baseline {baseline_id}. Generated by wa-agent new; edit freely.",
        f"# Set {', '.join('TF_VAR_' + e for e in build.get('env', DEFAULT_ENV))} in the environment; never commit secrets.",
    ], inputs)}
    for i, stage in enumerate(build["stages"], 1):
        files[f"stage-{i}-{stage['name']}.tfvars"] = render_tfvars(baseline, stage, i)
    files["README.md"] = render_readme(baseline, inputs, commit, book_dir)
    manifest = {
        "baseline": baseline_id,
        "catalog_version": catalog["version"],
        "placeholders": placeholders(build, inputs),
    }
    if "deployment" in build:
        paths = bundle_files(build["deployment"], repo_root)
        manifest.update(deployment=build["deployment"], source=REPO_URL, commit=commit,
                        matches_commit=matches_commit(paths, repo_root),
                        files={p: hashlib.sha256((repo_root / p).read_bytes()).hexdigest() for p in paths})
    else:
        manifest.update(source=build["source"])
    files["baseline.json"] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    files[".gitignore"] = "*.plan\n*.plan.json\n*.facts.json\nstate.json\n*.tfstate*\n.terraform/\ninputs.tfvars\n"
    return files


def generate(catalog: dict, baseline_id: str, out_dir: str, answers: dict | None = None,
             repo_root: Path = REPO_ROOT) -> list[Path]:
    """Write the run book (and, for repo deployments, the Terraform) into a new directory."""
    out = Path(out_dir)
    files = render(catalog, baseline_id, answers, repo_root, book_dir=out.resolve().as_posix())
    if out.exists():
        raise ValueError(f"{out_dir} already exists; the agent never overwrites, choose a new directory")
    build = {b["id"]: b for b in catalog["baselines"]}[baseline_id]["build"]
    out.mkdir(parents=True)
    written = []
    for name, content in files.items():
        (out / name).write_text(content, encoding="utf-8")
        written.append(out / name)
    if "deployment" in build:
        for rel in json.loads(files["baseline.json"])["files"]:
            target = out / "terraform" / rel
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes((repo_root / rel).read_bytes())
            written.append(target)
    return written
