"""New workspace: turn a baseline into a run book for a tested repo deployment.

The output is a new directory with layered tfvars per stage and a README.
Nothing existing is modified: the deployment in the repo is used as-is, the
user runs Terraform, and `verify` checks the resulting state afterwards.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

from .catalog import CATALOG_ROOT

REPO_ROOT = CATALOG_ROOT.parent.parent
REPO_URL = "https://github.com/bhavink/databricks"
PLACEHOLDER = "REPLACE_ME"


def declared_variables(deployment: str, repo_root: Path = REPO_ROOT) -> set[str]:
    text = (repo_root / deployment / "variables.tf").read_text(encoding="utf-8")
    return set(re.findall(r'^variable\s+"([A-Za-z0-9_]+)"', text, re.M))


def _hcl(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        return json.dumps(value)
    if isinstance(value, list):
        return "[" + ", ".join(_hcl(v) for v in value) + "]"
    raise ValueError(f"unsupported tfvars value: {value!r}")


def render_tfvars(baseline: dict, stage: dict, index: int) -> str:
    lines = [
        f"# Stage {index}: {stage['name']} — baseline {baseline['id']}",
        "# Generated by wa-agent new. Layer on top of your own terraform.tfvars;",
        "# later -var-file arguments override earlier ones.",
        "",
    ]
    width = max(len(k) for k in stage["tfvars"])
    lines += [f"{k:<{width}} = {_hcl(v)}" for k, v in sorted(stage["tfvars"].items())]
    return "\n".join(lines) + "\n"


def placeholders(build: dict) -> list[str]:
    found = set()
    for stage in build["stages"]:
        for key, value in stage["tfvars"].items():
            values = value if isinstance(value, list) else [value]
            if any(isinstance(v, str) and v.startswith(PLACEHOLDER) for v in values):
                found.add(key)
    return sorted(found)


def check_build(baseline: dict, repo_root: Path = REPO_ROOT) -> None:
    build = baseline.get("build")
    if not build:
        raise ValueError(
            f"baseline {baseline['id']!r} has no tested deployment in {REPO_URL} yet; "
            f"see {baseline['deployment']} and the official docs. The agent does not improvise Terraform."
        )
    declared = declared_variables(build["deployment"], repo_root)
    for stage in build["stages"]:
        unknown = sorted(set(stage["tfvars"]) - declared)
        if unknown:
            raise ValueError(f"baseline {baseline['id']} stage {stage['name']}: not variables of "
                             f"{build['deployment']}: {unknown}")


def render_readme(baseline: dict, ref: str, book_dir: str = "<run-book-dir>") -> str:
    build = baseline["build"]
    dep = build["deployment"]
    stages = build["stages"]
    var_files = []
    lines = [
        f"# New workspace — {baseline['name']}",
        "",
        f"Baseline `{baseline['id']}`: {baseline['use_case'].strip()}",
        "",
        f"Tested deployment: [`{dep}`]({REPO_URL}/tree/{ref}/{dep}) at `{ref}`.",
        "",
        "> The agent changed nothing. You run every command below; verify afterwards.",
        "",
        "## 0. Prepare",
        "",
        "```bash",
        f"git clone {REPO_URL}.git && cd databricks && git checkout {ref}",
        f"cd {dep}",
        "cp terraform.tfvars.example terraform.tfvars   # set prefix, region, resource group, CIDRs",
        "export TF_VAR_databricks_account_id=<account-id>         # bash/zsh; never commit credentials",
        "# PowerShell: $env:TF_VAR_databricks_account_id = \"<account-id>\"",
        "terraform init",
        "```",
        "",
    ]
    todo = placeholders(build)
    if todo:
        lines += ["Replace every `REPLACE_ME_*` value in the stage files: " + ", ".join(f"`{k}`" for k in todo) + ".", ""]
    for i, stage in enumerate(stages, 1):
        fname = f"stage-{i}-{stage['name']}.tfvars"
        var_files.append(f"-var-file={book_dir}/{fname}")
        args = " ".join(["-var-file=terraform.tfvars"] + var_files)
        lines += [f"## {i}. Stage: {stage['name']}", ""]
        if stage.get("note"):
            lines += [f"> {stage['note'].strip()}", ""]
        lines += [
            "```bash",
            f"terraform plan {args} -out stage{i}.plan",
            f"terraform show -json stage{i}.plan > stage{i}.plan.json",
            f"wa-agent collect tfplan --cloud azure --plan stage{i}.plan.json -o stage{i}.facts.json",
            f"wa-agent assess --facts stage{i}.facts.json --baseline {baseline['id']} -o stage{i}.report.md",
            f"terraform apply stage{i}.plan",
            "```",
            "",
        ]
    n = len(stages)
    lines += [
        f"## {n + 1}. Verify",
        "",
        "Check the deployed state against the baseline. Add live facts for controls that",
        "live outside Terraform state (e.g. manually approved NCC private endpoint rules).",
        "",
        "```bash",
        "terraform show -json > state.json",
        f"wa-agent verify --tf-json state.json --baseline {baseline['id']} -o verify.md",
        "# optional, from a network the workspace allows:",
        "wa-agent collect live --cloud azure --workspace <arm-id> --profile <ws> --account-profile <acct> -o live.facts.json",
        f"wa-agent verify --tf-json state.json --facts live.facts.json --baseline {baseline['id']} -o verify-live.md",
        "```",
        "",
        "Intermediate stages are expected to show gaps (for example public access still on);",
        "the final stage is the one that must verify as PASS.",
        "",
        "---",
        "",
        "_Provided as is, without warranty. Review and test before applying; you are responsible for what you deploy._",
        "",
    ]
    return "\n".join(lines)


def render(catalog: dict, baseline_id: str, ref: str = "master", repo_root: Path = REPO_ROOT,
           book_dir: str = "<run-book-dir>") -> dict[str, str]:
    """File name -> content for a baseline's run book. Writes nothing."""
    baselines = {b["id"]: b for b in catalog["baselines"]}
    if baseline_id not in baselines:
        raise ValueError(f"unknown baseline {baseline_id!r}; choose from {sorted(baselines)}")
    baseline = baselines[baseline_id]
    check_build(baseline, repo_root)
    files = {
        f"stage-{i}-{stage['name']}.tfvars": render_tfvars(baseline, stage, i)
        for i, stage in enumerate(baseline["build"]["stages"], 1)
    }
    files["README.md"] = render_readme(baseline, ref, book_dir)
    files["baseline.json"] = json.dumps({
        "baseline": baseline_id,
        "deployment": baseline["build"]["deployment"],
        "ref": ref,
        "catalog_version": catalog["version"],
        "placeholders": placeholders(baseline["build"]),
    }, indent=2, sort_keys=True) + "\n"
    files[".gitignore"] = "*.plan\n*.plan.json\n*.facts.json\nstate.json\n*.tfstate*\n"
    return files


def generate(catalog: dict, baseline_id: str, out_dir: str, ref: str = "master", repo_root: Path = REPO_ROOT) -> list[Path]:
    """Write the run book into a new directory (never an existing one)."""
    out = Path(out_dir)
    files = render(catalog, baseline_id, ref, repo_root, book_dir=out.resolve().as_posix())
    if out.exists():
        raise ValueError(f"{out_dir} already exists; the agent never overwrites, choose a new directory")
    out.mkdir(parents=True)
    written = []
    for name, content in files.items():
        (out / name).write_text(content, encoding="utf-8")
        written.append(out / name)
    return written
